[project]
name = "packagechecker"
author = "Nick Brisebois <email@nick-b.ca>"
version = "0.1.0"
description = "Check if Sims 4 CC files are corrupted or not"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.10.1",
]
